version: '3.8'

services:
  postgresql:
    image: postgres:alpine3.14
    container_name: pq-local
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_DB=nestjs_overview
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root
    restart: always

  redis:
    image: redis:alpine3.14
    container_name: redis-nestjs_overview
    ports:
      - "6379:6379"